### PR TITLE
Handle streams attached to an error by replacing them with `'[object Stream]'`

### PR DESCRIPTION
**Pull request by wodka**
fixes https://github.com/sindresorhus/serialize-error/issues/56

image

### CODE REVIEW

**Comment by Richienb** [comment]
If the module is going to handle readables, then what about writables and transform streams?

**Comment by Richienb** [comment]
Also, this can be used: https://www.npmjs.com/package/is-stream

**Comment by wodka** [comment]
> Also, this can be used: https://github.com/sindresorhus/is-stream

would make sense - what do you think about adding this as a dependency?

**Comment by sindresorhus** [comment]
This needs a test.

**Comment by sindresorhus** [comment]
> would make sense - what do you think about adding this as a dependency?

Nah. I think what you have is fine for now. https://github.com/sindresorhus/serialize-error/pull/57/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R80

**Comment by sindresorhus** [comment]
This also needs to support https://nodejs.org/api/webstreams.html#class-readablestream

**Comment by fregante** [comment]
Same applies here: https://github.com/sindresorhus/serialize-error/issues/55#issuecomment-1037943930

I didn't realize that `serialize-error` already includes `Buffer` accommodations. Even that one seems unrelated.

**Comment by sindresorhus** [comment]
>I didn't realize that serialize-error already includes Buffer accommodations. Even that one seems unrelated.

It's just to make the common use-case nicer. It's not meant for two-way transfer. It's mostly just to make it nicer for logging and storing errors.

**Comment by wodka** [comment]
@sindresorhus would you think it makes more sense to split it up to show a text depending on the stream type? Something along the lines of this:

```
		if (typeof value === 'object' && typeof value.pipe === 'function') {
			const writeable = typeof value._write === 'function' && typeof value._writableState === 'object';
			const readable = typeof value._read === 'function' && typeof value._readableState === 'object';

			if (writeable && readable && typeof value._transform === 'function') {
				to[key] = '[object TransformStream]';
				continue;
			}

			if (writeable && readable) {
				to[key] = '[object DuplexStream]';
				continue;
			}

			if (readable) {
				to[key] = '[object ReadableStream]';
				continue;
			}

			if (writeable) {
				to[key] = '[object WriteableStream]';
				continue;
			}

			to[key] = '[object Stream]';
			continue;
		}
```

**Comment by sindresorhus** [comment]
> would you think it makes more sense to split it up to show a text depending on the stream type? Something along the lines of this:

No, let's keep it simple.

**Comment by wodka** [comment]
ok, then I think it's done

**Pull request merged**
