### PR TITLE
Make it work better in the browser

### LINKED ISSUE #26: change in v5: `const {inspect} = require('util');` can lead to web bundle bloat
This was added in v5 for `deserializeError`:

```ts
const {inspect} = require('util');
```

This adds about 8KB to web bundles, which can be significant, especially in projects not using `deserializeError`.

Possible solutions:

* Not worry about 8KB and tell developers to use v4 if bundle size is of concern.
* Separate `serializeError` into a separate file that can be imported without the `deserializeError` code.
* Separate `deserializeError` into a new module.
* Publish code with ES6-style `import`, add `sideEffects: false` to the `package.json` to enable tree shaking in the module.
* Other ideas?

### PR DESCRIPTION
**Pull request by vladimiry**
Fixes #26

### CODE REVIEW

**Comment by vladimiry** [comment]
Fixing nodejs 8 case.

**Comment by sindresorhus** [comment]
Please don't uncheck the checkbox that allows me to do changes to the PR.

**Comment by vladimiry** [comment]
> Please don't uncheck the checkbox that allows me to do changes to the PR.

Where do I see that checkbox?

I don't see the checkbox on the page as described in https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork.

**Comment by sindresorhus** [comment]
I assumed you unchecked it. Maybe you didn't. Maybe it's because you're doing the pull request from `master` branch, which you really shouldn't. Pull requests should *always* be done from a separate branch.

**Comment by vladimiry** [comment]
> Maybe it's because you're doing the pull request from master branch, which you really shouldn't. Pull requests should always be done from a separate branch.

Still no checkbox if non-master branch involved:

no-difference

GET https://api.github.com/repos/sindresorhus/serialize-error/pulls/27 gives `maintainer_can_modify: false` value. But I just sent PATCH https://api.github.com/repos/sindresorhus/serialize-error/pulls/27 with needed parameters and `maintainer_can_modify` is `true` now. Can you try modifying the stuff?

**Comment by sindresorhus** [comment]
The "Edit" button is there now, so either you changed something or this was a temporary GitHub bug.

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by vladimiry** [comment]
>  The "Edit" button is there now, so either you changed something or this was a temporary GitHub bug.

As I wrote above I called PATCH https://api.github.com/repos/sindresorhus/serialize-error/pulls/27 API directly passing needed parameters to the request in order to enabled the `maintainer_can_modify` flag and it worked out.

**Comment by sindresorhus** [comment]
Ah, I missed the text below the image.

**Pull request merged**
